import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'

const currentDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(currentDir, '../../..')

test('tauri host uses invoke bridge without a packaged stdio sidecar RPC layer', async () => {
  const tauriBridgeSource = await readFile(path.join(repoRoot, 'frontend/tauri/runtimeBridge.ts'), 'utf8')
  const desktopBridgeSource = await readFile(path.join(repoRoot, 'frontend/desktop/runtimeBridge.ts'), 'utf8')
  const tauriRendererSource = await readFile(path.join(repoRoot, 'frontend/tauri/renderer.tsx'), 'utf8')
  const rustSource = await readFile(path.join(repoRoot, 'src-tauri/src/main.rs'), 'utf8')
  const runtimeSource = await readFile(path.join(repoRoot, 'src-tauri/src/runtime.rs'), 'utf8')
  const backendRuntimeSource = await readFile(path.join(repoRoot, 'src-tauri/src/runtime/backend.rs'), 'utf8')
  const cargoToml = await readFile(path.join(repoRoot, 'src-tauri/Cargo.toml'), 'utf8')
  const tauriConfig = await readFile(path.join(repoRoot, 'src-tauri/tauri.conf.json'), 'utf8')

  assert.match(tauriBridgeSource, /from '@tauri-apps\/api\/core'/)
  assert.match(tauriBridgeSource, /invoke\(/)
  assert.match(tauriBridgeSource, /createDesktopRuntimeBridge\(/)
  assert.doesNotMatch(tauriBridgeSource, /\.\.\/electron\/runtime\/runtimeBridge/)
  assert.doesNotMatch(tauriBridgeSource, /backend_invoke_capability/)
  assert.doesNotMatch(tauriBridgeSource, /app:get-version|plugins:list|backend:invoke-capability/)
  assert.match(tauriBridgeSource, /app\.version\.get/)
  assert.match(tauriBridgeSource, /backend\.capability\.invoke/)
  assert.match(tauriBridgeSource, /open:\s*'dialog\.open'/)
  assert.match(tauriBridgeSource, /execBundled:\s*'process\.bundled\.exec'/)
  assert.doesNotMatch(tauriBridgeSource, /open:\s*'dialog\.folder\.open'/)
  assert.match(tauriBridgeSource, /runtime_invoke', \{ operation, args \}/)
  assert.match(desktopBridgeSource, /createPrestoRuntime\(/)
  assert.match(tauriRendererSource, /createTauriRuntimeBridge\(\)/)
  assert.doesNotMatch(tauriRendererSource, /invoke\('app_ready'\)/)
  assert.doesNotMatch(tauriRendererSource, /onReady:/)
  assert.doesNotMatch(tauriRendererSource, /setTimeout\(/)
  assert.doesNotMatch(tauriRendererSource, /requestAnimationFrame/)
  assert.doesNotMatch(tauriRendererSource, /__PRESTO_BOOTSTRAP__/)
  assert.doesNotMatch(rustSource, /spawn_sidecar/)
  assert.doesNotMatch(rustSource, /SidecarProcess/)
  assert.doesNotMatch(rustSource, /stdin/)
  assert.doesNotMatch(rustSource, /stdout/)
  assert.doesNotMatch(rustSource, /backend_invoke_capability/)
  assert.doesNotMatch(rustSource, /app:get-version|plugins:list|backend:invoke-capability/)
  assert.match(rustSource, /app\.version\.get/)
  assert.match(rustSource, /backend\.capability\.invoke/)
  assert.match(runtimeSource, /mod backend;/)
  assert.match(runtimeSource, /mod plugins;/)
  assert.match(runtimeSource, /mod mobile_progress;/)
  assert.match(runtimeSource, /"dialog\.open"\s*=>/)
  assert.match(runtimeSource, /"process\.bundled\.exec"\s*=>/)
  assert.match(runtimeSource, /pick_file\(\)/)
  assert.match(runtimeSource, /pick_folder\(\)/)
  assert.match(backendRuntimeSource, /backend_process_exit/)
  assert.match(backendRuntimeSource, /"reason":\s*reason/)
  assert.doesNotMatch(runtimeSource, /shutdown\(Shutdown::Write\)/)
  assert.doesNotMatch(rustSource, /fn app_ready/)
  assert.match(rustSource, /if cfg!\(debug_assertions\) \{\s*return Ok\(repo_root\(\)\);/m)
  assert.doesNotMatch(rustSource, /get_webview_window\("splashscreen"\)/)
  assert.match(cargoToml, /\[package\]/)
  assert.match(cargoToml, /tauri/)
  assert.match(tauriConfig, /"label": "main"/)
  assert.doesNotMatch(tauriConfig, /"visible": false/)
  assert.doesNotMatch(tauriConfig, /"label": "splashscreen"/)
  assert.doesNotMatch(tauriConfig, /"url": "\/splashscreen.html"/)
  assert.match(tauriConfig, /"backgroundColor":\s*\[\s*12,\s*14,\s*23,\s*255\s*\]/)
})
