export const hostShellColors = {
  canvas: '#f7f8fc',
  surface: '#ffffff',
  surfaceMuted: '#f2f4fa',
  surfaceRaised: '#edf0f7',
  surfaceSelected: '#e7e4ff',
  border: '#c8cedd',
  borderStrong: '#b8c0d4',
  text: '#171a24',
  textMuted: '#525b71',
  textSubtle: '#77809a',
  accent: '#5b4ed6',
  accentSoft: '#e7e4ff',
  successBorder: '#bad7c7',
  successSurface: '#edf7f1',
  successText: '#2f6d52',
  errorBorder: '#e6c3bf',
  errorSurface: '#fcebea',
  errorText: '#91413a',
} as const
