export type CapabilityKind = 'query' | 'command' | 'job'

export type CapabilityVisibility = 'public' | 'internal'

export type CapabilityDomain =
  | 'system'
  | 'config'
  | 'ai'
  | 'daw'
  | 'automation'
  | 'session'
  | 'track'
  | 'clip'
  | 'transport'
  | 'import'
  | 'stripSilence'
  | 'export'
  | 'jobs'

export type CapabilityDependency =
  | 'config_store'
  | 'keychain_store'
  | 'ai_service'
  | 'jobs'
  | 'daw'
  | 'mac_automation'
  | 'daw_ui_profile'

export type PublicCapabilityId =
  | 'system.health'
  | 'config.get'
  | 'config.update'
  | 'daw.connection.connect'
  | 'daw.connection.disconnect'
  | 'daw.connection.getStatus'
  | 'daw.adapter.getSnapshot'
  | 'automation.splitStereoToMono.execute'
  | 'session.getInfo'
  | 'session.getLength'
  | 'session.save'
  | 'session.applySnapshot'
  | 'session.getSnapshotInfo'
  | 'track.list'
  | 'track.listNames'
  | 'track.selection.get'
  | 'track.rename'
  | 'track.select'
  | 'track.color.apply'
  | 'track.pan.set'
  | 'track.mute.set'
  | 'track.solo.set'
  | 'clip.selectAllOnTrack'
  | 'transport.play'
  | 'transport.stop'
  | 'transport.record'
  | 'transport.getStatus'
  | 'import.run.start'
  | 'stripSilence.open'
  | 'stripSilence.execute'
  | 'export.range.set'
  | 'export.start'
  | 'export.direct.start'
  | 'export.run.start'
  | 'export.mixWithSource'
  | 'jobs.create'
  | 'jobs.update'
  | 'jobs.get'
  | 'jobs.list'
  | 'jobs.cancel'
  | 'jobs.delete'

export type InternalCapabilityId =
  | 'session.requireOpen'
  | 'track.requireAnySelected'
  | 'daw.requireMinimumVersion'
  | 'trackColor.requireSupport'
  | 'audio.importOne'
  | 'audio.importBatch'
  | 'export.cancel'
  | 'export.isCancelled'
  | 'mac.preflightAccessibility'
  | 'track.color.applyViaUi'
  | 'stripSilence.openViaUi'
  | 'stripSilence.executeViaUi'

export type CapabilityId = PublicCapabilityId | InternalCapabilityId
