"""Auto-generated from PTSL.proto; do not edit by hand."""
from __future__ import annotations

PTSL_COMMAND_CATALOG = (
    {
        "command_name": "CId_CreateSession",
        "command_id": 0,
        "request_message": "CreateSessionRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_OpenSession",
        "command_id": 1,
        "request_message": "OpenSessionRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Import",
        "command_id": 2,
        "request_message": "ImportRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetTrackList",
        "command_id": 3,
        "request_message": "GetTrackListRequestBody",
        "response_message": "GetTrackListResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SelectAllClipsOnTrack",
        "command_id": 4,
        "request_message": "SelectAllClipsOnTrackRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ExtendSelectionToTargetTracks",
        "command_id": 5,
        "request_message": "ExtendSelectionToTargetTracksRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_TrimToSelection",
        "command_id": 6,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_CreateFadesBasedOnPreset",
        "command_id": 7,
        "request_message": "CreateFadesBasedOnPresetRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_RenameTargetTrack",
        "command_id": 8,
        "request_message": "RenameTargetTrackRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ConsolidateClip",
        "command_id": 9,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ExportClipsAsFiles",
        "command_id": 10,
        "request_message": "ExportClipsAsFilesRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "export",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ExportSelectedTracksAsAAFOMF",
        "command_id": 11,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "export",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetTaskStatus",
        "command_id": 12,
        "request_message": "GetTaskStatusRequestBody",
        "response_message": "GetTaskStatusResponseBody",
        "has_py_ptsl_op": True,
        "category": "general",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_HostReadyCheck",
        "command_id": 13,
        "request_message": None,
        "response_message": "HostReadyCheckResponseBody",
        "has_py_ptsl_op": True,
        "category": "general",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_RefreshTargetAudioFiles",
        "command_id": 14,
        "request_message": "RefreshTargetAudioFilesRequestBody",
        "response_message": "RefreshTargetAudioFilesResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_RefreshAllModifiedAudioFiles",
        "command_id": 15,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetFileLocation",
        "command_id": 16,
        "request_message": "GetFileLocationRequestBody",
        "response_message": "GetFileLocationResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_CloseSession",
        "command_id": 17,
        "request_message": "CloseSessionRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SaveSession",
        "command_id": 18,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SaveSessionAs",
        "command_id": 19,
        "request_message": "SaveSessionAsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Cut",
        "command_id": 20,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Copy",
        "command_id": 21,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Paste",
        "command_id": 22,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Clear",
        "command_id": 23,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_CutSpecial",
        "command_id": 24,
        "request_message": "CutSpecialRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_CopySpecial",
        "command_id": 25,
        "request_message": "CopySpecialRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ClearSpecial",
        "command_id": 26,
        "request_message": "ClearSpecialRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_PasteSpecial",
        "command_id": 27,
        "request_message": "PasteSpecialRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ExportMix",
        "command_id": 28,
        "request_message": "ExportMixRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "export",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_Spot",
        "command_id": 29,
        "request_message": "SpotRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ExportSessionInfoAsText",
        "command_id": 30,
        "request_message": "ExportSessionInfoAsTextRequestBody",
        "response_message": "ExportSessionInfoAsTextResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_file",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetDynamicProperties",
        "command_id": 31,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "general",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetPlaybackMode",
        "command_id": 32,
        "request_message": "SetPlaybackModeRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetRecordMode",
        "command_id": 33,
        "request_message": "SetRecordModeRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionAudioFormat",
        "command_id": 34,
        "request_message": None,
        "response_message": "GetSessionAudioFormatResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionSampleRate",
        "command_id": 35,
        "request_message": None,
        "response_message": "GetSessionSampleRateResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionBitDepth",
        "command_id": 36,
        "request_message": None,
        "response_message": "GetSessionBitDepthResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionInterleavedState",
        "command_id": 37,
        "request_message": None,
        "response_message": "GetSessionInterleavedStateResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionTimeCodeRate",
        "command_id": 38,
        "request_message": None,
        "response_message": "GetSessionTimeCodeRateResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionFeetFramesRate",
        "command_id": 39,
        "request_message": None,
        "response_message": "GetSessionFeetFramesRateResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionAudioRatePullSettings",
        "command_id": 40,
        "request_message": None,
        "response_message": "GetSessionAudioRatePullSettingsResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionVideoRatePullSettings",
        "command_id": 41,
        "request_message": None,
        "response_message": "GetSessionVideoRatePullSettingsResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionName",
        "command_id": 42,
        "request_message": None,
        "response_message": "GetSessionNameResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionPath",
        "command_id": 43,
        "request_message": None,
        "response_message": "GetSessionPathResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionStartTime",
        "command_id": 44,
        "request_message": None,
        "response_message": "GetSessionStartTimeResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetSessionLength",
        "command_id": 45,
        "request_message": None,
        "response_message": "GetSessionLengthResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionAudioFormat",
        "command_id": 46,
        "request_message": "SetSessionAudioFormatRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionBitDepth",
        "command_id": 47,
        "request_message": "SetSessionBitDepthRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionInterleavedState",
        "command_id": 48,
        "request_message": "SetSessionInterleavedStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionTimeCodeRate",
        "command_id": 49,
        "request_message": "SetSessionTimeCodeRateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionFeetFramesRate",
        "command_id": 50,
        "request_message": "SetSessionFeetFramesRateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionAudioRatePullSettings",
        "command_id": 51,
        "request_message": "SetSessionAudioRatePullSettingsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionVideoRatePullSettings",
        "command_id": 52,
        "request_message": "SetSessionVideoRatePullSettingsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionStartTime",
        "command_id": 53,
        "request_message": "SetSessionStartTimeRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_SetSessionLength",
        "command_id": 54,
        "request_message": "SetSessionLengthRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetPTSLVersion",
        "command_id": 55,
        "request_message": None,
        "response_message": "GetPTSLVersionResponseBody",
        "has_py_ptsl_op": True,
        "category": "general",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetPlaybackMode",
        "command_id": 56,
        "request_message": None,
        "response_message": "GetPlaybackModeResponseBody",
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetRecordMode",
        "command_id": 57,
        "request_message": None,
        "response_message": "GetRecordModeResponseBody",
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetTransportArmed",
        "command_id": 58,
        "request_message": None,
        "response_message": "GetTransportArmedResponseBody",
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_GetTransportState",
        "command_id": 59,
        "request_message": None,
        "response_message": "GetTransportStateResponseBody",
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2022.12.0",
    },
    {
        "command_name": "CId_ClearMemoryLocation",
        "command_id": 61,
        "request_message": "ClearMemoryLocationRequestBody",
        "response_message": "ClearMemoryLocationResponseBody",
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_RenameSelectedClip",
        "command_id": 62,
        "request_message": "RenameSelectedClipRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_RenameTargetClip",
        "command_id": 63,
        "request_message": "RenameTargetClipRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_TogglePlayState",
        "command_id": 64,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_ToggleRecordEnable",
        "command_id": 65,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_PlayHalfSpeed",
        "command_id": 66,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_RecordHalfSpeed",
        "command_id": 67,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_EditMemoryLocation",
        "command_id": 68,
        "request_message": "EditMemoryLocationRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_GetMemoryLocations",
        "command_id": 69,
        "request_message": "GetMemoryLocationsRequestBody",
        "response_message": "GetMemoryLocationsResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_RegisterConnection",
        "command_id": 70,
        "request_message": "RegisterConnectionRequestBody",
        "response_message": "RegisterConnectionResponseBody",
        "has_py_ptsl_op": True,
        "category": "general",
        "minimum_host_version": "2023.03.0",
    },
    {
        "command_name": "CId_CreateMemoryLocation",
        "command_id": 71,
        "request_message": "CreateMemoryLocationRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.06.0",
    },
    {
        "command_name": "CId_CreateNewTracks",
        "command_id": 72,
        "request_message": "CreateNewTracksRequestBody",
        "response_message": "CreateNewTracksResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_SelectTracksByName",
        "command_id": 73,
        "request_message": "SelectTracksByNameRequestBody",
        "response_message": "SelectTracksByNameResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_GetEditMode",
        "command_id": 74,
        "request_message": None,
        "response_message": "GetEditModeResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_SetEditMode",
        "command_id": 75,
        "request_message": "SetEditModeRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_GetEditTool",
        "command_id": 76,
        "request_message": None,
        "response_message": "GetEditToolResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_SetEditTool",
        "command_id": 77,
        "request_message": "SetEditToolRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_RecallZoomPreset",
        "command_id": 78,
        "request_message": "RecallZoomPresetRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_GetEditModeOptions",
        "command_id": 79,
        "request_message": None,
        "response_message": "GetEditModeOptionsResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_SetEditModeOptions",
        "command_id": 80,
        "request_message": "SetEditModeOptionsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_SetTimelineSelection",
        "command_id": 81,
        "request_message": "SetTimelineSelectionRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_GetTimelineSelection",
        "command_id": 82,
        "request_message": "GetTimelineSelectionRequestBody",
        "response_message": "GetTimelineSelectionResponseBody",
        "has_py_ptsl_op": True,
        "category": "transport",
        "minimum_host_version": "2023.09.0",
    },
    {
        "command_name": "CId_ImportVideo",
        "command_id": 83,
        "request_message": "ImportVideoRequestBody",
        "response_message": "ImportVideoResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_write",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SelectMemoryLocation",
        "command_id": 84,
        "request_message": "SelectMemoryLocationRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackMuteState",
        "command_id": 85,
        "request_message": "SetTrackMuteStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackSoloState",
        "command_id": 86,
        "request_message": "SetTrackSoloStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackSoloSafeState",
        "command_id": 87,
        "request_message": "SetTrackSoloSafeStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackRecordEnableState",
        "command_id": 88,
        "request_message": "SetTrackRecordEnableStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackRecordSafeEnableState",
        "command_id": 89,
        "request_message": "SetTrackRecordSafeEnableStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackInputMonitorState",
        "command_id": 90,
        "request_message": "SetTrackInputMonitorStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackSmartDspState",
        "command_id": 91,
        "request_message": "SetTrackSmartDspStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackHiddenState",
        "command_id": 92,
        "request_message": "SetTrackHiddenStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackInactiveState",
        "command_id": 93,
        "request_message": "SetTrackInactiveStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackFrozenState",
        "command_id": 94,
        "request_message": "SetTrackFrozenStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackOnlineState",
        "command_id": 95,
        "request_message": "SetTrackOnlineStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_SetTrackOpenState",
        "command_id": 96,
        "request_message": "SetTrackOpenStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2023.12.0",
    },
    {
        "command_name": "CId_GetSessionIDs",
        "command_id": 97,
        "request_message": None,
        "response_message": "GetSessionIDsResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_file",
        "minimum_host_version": "2024.03.0",
    },
    {
        "command_name": "CId_GetMemoryLocationsManageMode",
        "command_id": 98,
        "request_message": None,
        "response_message": "GetMemoryLocationsManageModeResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_SetMemoryLocationsManageMode",
        "command_id": 99,
        "request_message": "SetMemoryLocationsManageModeRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_SetMainCounterFormat",
        "command_id": 100,
        "request_message": "SetMainCounterFormatRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_SetSubCounterFormat",
        "command_id": 101,
        "request_message": "SetSubCounterFormatRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "session_write",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_GetMainCounterFormat",
        "command_id": 102,
        "request_message": None,
        "response_message": "GetMainCounterFormatResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_GetSubCounterFormat",
        "command_id": 103,
        "request_message": None,
        "response_message": "GetSubCounterFormatResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_Undo",
        "command_id": 104,
        "request_message": "UndoRequestBody",
        "response_message": "UndoResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_Redo",
        "command_id": 105,
        "request_message": "RedoRequestBody",
        "response_message": "RedoResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_UndoAll",
        "command_id": 106,
        "request_message": None,
        "response_message": "UndoAllResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_RedoAll",
        "command_id": 107,
        "request_message": None,
        "response_message": "RedoAllResponseBody",
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_ClearUndoQueue",
        "command_id": 108,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_SetTrackDSPModeSafeState",
        "command_id": 109,
        "request_message": "SetTrackDSPModeSafeStateRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_GetSessionSystemDelayInfo",
        "command_id": 110,
        "request_message": None,
        "response_message": "GetSessionSystemDelayInfoResponseBody",
        "has_py_ptsl_op": True,
        "category": "session_read",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_GroupClips",
        "command_id": 111,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_UngroupClips",
        "command_id": 112,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_UngroupAllClips",
        "command_id": 113,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_RegroupClips",
        "command_id": 114,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_RepeatSelection",
        "command_id": 115,
        "request_message": "RepeatSelectionRequestBody",
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_DuplicateSelection",
        "command_id": 116,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": True,
        "category": "editing",
        "minimum_host_version": "2024.06.0",
    },
    {
        "command_name": "CId_ClearAllMemoryLocations",
        "command_id": 117,
        "request_message": None,
        "response_message": "ClearAllMemoryLocationsResponseBody",
        "has_py_ptsl_op": True,
        "category": None,
        "minimum_host_version": "2024.10.0",
    },
    {
        "command_name": "CId_GetTimeAsType",
        "command_id": 118,
        "request_message": "GetTimeAsTypeRequestBody",
        "response_message": "GetTimeAsTypeResponseBody",
        "has_py_ptsl_op": False,
        "category": "time_utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SubtractLocations",
        "command_id": 119,
        "request_message": "SubtractLocationsRequestBody",
        "response_message": "SubtractLocationsResponseBody",
        "has_py_ptsl_op": False,
        "category": "time_utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_AddLengthToLocation",
        "command_id": 120,
        "request_message": "AddLengthToLocationRequestBody",
        "response_message": "AddLengthToLocationResponseBody",
        "has_py_ptsl_op": False,
        "category": "time_utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SubtractPositions",
        "command_id": 121,
        "request_message": "SubtractPositionsRequestBody",
        "response_message": "SubtractPositionsResponseBody",
        "has_py_ptsl_op": False,
        "category": "time_utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_AddLengthToPosition",
        "command_id": 122,
        "request_message": "AddLengthToPositionRequestBody",
        "response_message": "AddLengthToPositionResponseBody",
        "has_py_ptsl_op": False,
        "category": "time_utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_ImportAudioToClipList",
        "command_id": 123,
        "request_message": "ImportAudioToClipListRequestBody",
        "response_message": "ImportAudioToClipListResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_write",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SpotClipsByID",
        "command_id": 124,
        "request_message": "SpotClipsByIDRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetClipList",
        "command_id": 125,
        "request_message": "GetClipListRequestBody",
        "response_message": "GetClipListResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_read",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetMediaFileInfo",
        "command_id": 126,
        "request_message": "GetMediaFileInfoRequestBody",
        "response_message": "GetMediaFileInfoResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_read",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_CreateAudioClips",
        "command_id": 127,
        "request_message": "CreateAudioClipsRequestBody",
        "response_message": "CreateAudioClipsResponseBody",
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetExportMixSourceList",
        "command_id": 128,
        "request_message": "GetExportMixSourceListRequestBody",
        "response_message": "GetExportMixSourceListResponseBody",
        "has_py_ptsl_op": False,
        "category": None,
        "minimum_host_version": "2025.06.0",
    },
    {
        "command_name": "CId_CreateBatchJob",
        "command_id": 129,
        "request_message": "CreateBatchJobRequestBody",
        "response_message": "CreateBatchJobResponseBody",
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetMonitorOutputPath",
        "command_id": 130,
        "request_message": None,
        "response_message": "GetMonitorOutputPathResponseBody",
        "has_py_ptsl_op": True,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetEditSelection",
        "command_id": 131,
        "request_message": "GetEditSelectionRequestBody",
        "response_message": "GetEditSelectionResponseBody",
        "has_py_ptsl_op": True,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SubscribeToEvents",
        "command_id": 132,
        "request_message": "SubscribeToEventsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetBatchJobStatus",
        "command_id": 133,
        "request_message": "GetBatchJobStatusRequestBody",
        "response_message": "GetBatchJobStatusResponseBody",
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_BounceTrack",
        "command_id": 134,
        "request_message": "BounceTrackRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "export",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_PollEvents",
        "command_id": 135,
        "request_message": None,
        "response_message": "PollEventsResponseBody",
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_UnsubscribeFromEvents",
        "command_id": 136,
        "request_message": "UnsubscribeFromEventsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_CompleteBatchJob",
        "command_id": 137,
        "request_message": "CompleteBatchJobRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_CancelBatchJob",
        "command_id": 138,
        "request_message": "CancelBatchJobRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_BeginScrub",
        "command_id": 139,
        "request_message": "BeginScrubRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_EndScrub",
        "command_id": 140,
        "request_message": None,
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_ContinueScrub",
        "command_id": 141,
        "request_message": "ContinueScrubRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_EnableCueProVideoPlugIn",
        "command_id": 142,
        "request_message": "EnableCueProVideoPlugInRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "private_api",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_UpdateVideo",
        "command_id": 143,
        "request_message": "UpdateVideoRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_EnableAPI",
        "command_id": 144,
        "request_message": "EnableAPIRequestBody",
        "response_message": "EnableAPIResponseBody",
        "has_py_ptsl_op": False,
        "category": "private_api",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_ExchangePublicKeys",
        "command_id": 145,
        "request_message": "ExchangePublicKeysRequestBody",
        "response_message": "ExchangePublicKeysResponseBody",
        "has_py_ptsl_op": False,
        "category": "private_api",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_CreateSignalPath",
        "command_id": 146,
        "request_message": "CreateSignalPathRequestBody",
        "response_message": "CreateSignalPathResponseBody",
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SetTrackMainOutputAssignments",
        "command_id": 147,
        "request_message": "SetTrackMainOutputAssignmentsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetTrackControlInfo",
        "command_id": 148,
        "request_message": "GetTrackControlInfoRequestBody",
        "response_message": "GetTrackControlInfoResponseBody",
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetTrackControlBreakpoints",
        "command_id": 149,
        "request_message": "GetTrackControlBreakpointsRequestBody",
        "response_message": "GetTrackControlBreakpointsResponseBody",
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SetTrackControlBreakpoints",
        "command_id": 150,
        "request_message": "SetTrackControlBreakpointsRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_InstallMenuHandler",
        "command_id": 151,
        "request_message": "InstallMenuHandlerRequestBody",
        "response_message": "InstallMenuHandlerResponseBody",
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_UninstallMenuHandler",
        "command_id": 152,
        "request_message": "UninstallMenuHandlerRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SetTrackColor",
        "command_id": 153,
        "request_message": "SetTrackColorRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetTrackPlaylists",
        "command_id": 154,
        "request_message": "GetTrackPlaylistsRequestBody",
        "response_message": "GetTrackPlaylistsResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_read",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_SetTrackTimebase",
        "command_id": 155,
        "request_message": "SetTrackTimebaseRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetColorPalette",
        "command_id": 156,
        "request_message": "GetColorPaletteRequestBody",
        "response_message": "GetColorPaletteResponseBody",
        "has_py_ptsl_op": False,
        "category": "utility",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_DeleteTracks",
        "command_id": 157,
        "request_message": "DeleteTracksRequestBody",
        "response_message": None,
        "has_py_ptsl_op": False,
        "category": "editing",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_GetPlaylistElements",
        "command_id": 158,
        "request_message": "GetPlaylistElementsRequestBody",
        "response_message": "GetPlaylistElementsResponseBody",
        "has_py_ptsl_op": False,
        "category": "session_read",
        "minimum_host_version": "2025.10.0",
    },
    {
        "command_name": "CId_WriteSelectedTranscriptionToJSONFile",
        "command_id": 159,
        "request_message": None,
        "response_message": "WriteSelectedTranscriptionToJSONFileResponseBody",
        "has_py_ptsl_op": False,
        "category": "export",
        "minimum_host_version": "2025.10.0",
    },
)
